version: '3.8'

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: novabank_auth
      POSTGRES_USER: novabank
      POSTGRES_PASSWORD: novabank
    ports:
      - "5432:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data

volumes:
  postgres-auth-data:
